//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CheckInDateField;
        
        private string GuestNameField;
        
        private string HotelNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate
        {
            get
            {
                return this.CheckInDateField;
            }
            set
            {
                this.CheckInDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuestName
        {
            get
            {
                return this.GuestNameField;
            }
            set
            {
                this.GuestNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName
        {
            get
            {
                return this.HotelNameField;
            }
            set
            {
                this.HotelNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingResponse", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public partial class BookingResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BookingReferenceField;
        
        private bool IsApprovedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingReference
        {
            get
            {
                return this.BookingReferenceField;
            }
            set
            {
                this.BookingReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this.IsApprovedField;
            }
            set
            {
                this.IsApprovedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameUserField;
        
        private string PasswordField;
        
        private string RequestField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUser
        {
            get
            {
                return this.NameUserField;
            }
            set
            {
                this.NameUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElSalvadorHotels", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public partial class ElSalvadorHotels : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryField;
        
        private string DepartmentLocationField;
        
        private int IDHotelField;
        
        private string NameHotelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentLocation
        {
            get
            {
                return this.DepartmentLocationField;
            }
            set
            {
                this.DepartmentLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDHotel
        {
            get
            {
                return this.IDHotelField;
            }
            set
            {
                this.IDHotelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameHotel
        {
            get
            {
                return this.NameHotelField;
            }
            set
            {
                this.NameHotelField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHotelBookingService")]
public interface IHotelBookingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/BookHotel", ReplyAction="http://tempuri.org/IHotelBookingService/BookHotelResponse")]
    Service.BookingResponse BookHotel(Service.Reservation reservation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/BookHotel", ReplyAction="http://tempuri.org/IHotelBookingService/BookHotelResponse")]
    System.Threading.Tasks.Task<Service.BookingResponse> BookHotelAsync(Service.Reservation reservation);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/Authenticate", ReplyAction="http://tempuri.org/IHotelBookingService/AuthenticateResponse")]
    bool Authenticate(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/Authenticate", ReplyAction="http://tempuri.org/IHotelBookingService/AuthenticateResponse")]
    System.Threading.Tasks.Task<bool> AuthenticateAsync(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsList", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListResponse")]
    Service.ElSalvadorHotels[] GetHotelsList(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsList", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListResponse")]
    System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListAsync(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByCategory", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByCategoryResponse")]
    Service.ElSalvadorHotels[] GetHotelsListByCategory(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByCategory", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByCategoryResponse")]
    System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByCategoryAsync(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByLocation", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByLocationResponse")]
    Service.ElSalvadorHotels[] GetHotelsListByLocation(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByLocation", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByLocationResponse")]
    System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByLocationAsync(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByID", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByIDResponse")]
    Service.ElSalvadorHotels[] GetHotelsListByID(Service.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelBookingService/GetHotelsListByID", ReplyAction="http://tempuri.org/IHotelBookingService/GetHotelsListByIDResponse")]
    System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByIDAsync(Service.User user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHotelBookingServiceChannel : IHotelBookingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HotelBookingServiceClient : System.ServiceModel.ClientBase<IHotelBookingService>, IHotelBookingService
{
    
    public HotelBookingServiceClient()
    {
    }
    
    public HotelBookingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HotelBookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelBookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelBookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Service.BookingResponse BookHotel(Service.Reservation reservation)
    {
        return base.Channel.BookHotel(reservation);
    }
    
    public System.Threading.Tasks.Task<Service.BookingResponse> BookHotelAsync(Service.Reservation reservation)
    {
        return base.Channel.BookHotelAsync(reservation);
    }
    
    public bool Authenticate(Service.User user)
    {
        return base.Channel.Authenticate(user);
    }
    
    public System.Threading.Tasks.Task<bool> AuthenticateAsync(Service.User user)
    {
        return base.Channel.AuthenticateAsync(user);
    }
    
    public Service.ElSalvadorHotels[] GetHotelsList(Service.User user)
    {
        return base.Channel.GetHotelsList(user);
    }
    
    public System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListAsync(Service.User user)
    {
        return base.Channel.GetHotelsListAsync(user);
    }
    
    public Service.ElSalvadorHotels[] GetHotelsListByCategory(Service.User user)
    {
        return base.Channel.GetHotelsListByCategory(user);
    }
    
    public System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByCategoryAsync(Service.User user)
    {
        return base.Channel.GetHotelsListByCategoryAsync(user);
    }
    
    public Service.ElSalvadorHotels[] GetHotelsListByLocation(Service.User user)
    {
        return base.Channel.GetHotelsListByLocation(user);
    }
    
    public System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByLocationAsync(Service.User user)
    {
        return base.Channel.GetHotelsListByLocationAsync(user);
    }
    
    public Service.ElSalvadorHotels[] GetHotelsListByID(Service.User user)
    {
        return base.Channel.GetHotelsListByID(user);
    }
    
    public System.Threading.Tasks.Task<Service.ElSalvadorHotels[]> GetHotelsListByIDAsync(Service.User user)
    {
        return base.Channel.GetHotelsListByIDAsync(user);
    }
}
